### ISSUE TITLE
readme issues

### ISSUE THREAD

**Issue by tomasferrerasdev** [tomasferrerasdev/unbridled-spirit#4]
![paypal-modal](https://user-images.githubusercontent.com/107090584/184007295-0b0124ce-544f-43c1-9815-e8d497b20a42.png)
![fermium](https://user-images.githubusercontent.com/107090584/184007300-374b9f80-d50b-4374-9787-21373ce45831.png)

**Comment by LoftyDroid** [comment]
Can you please explain the issue if the issue is still open, I would like to contribute

**Comment by tomasferrerasdev** [comment]
> Can you please explain the issue if the issue is still open, I would like to contribute

Hello Ahmed, the issue should have been closed weeks ago, anyway I thank you for the initiative
